theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
url: "https://SangjinKO.github.io" # the base hostname & protocol for your site 
baseurl: "" # the subpath of your site, e.g. "/blog"
